/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db */
        get: operations["health_db_api_v1_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Me */
        get: operations["auth_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Summary */
        get: operations["ai_summary_api_v1_ai_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Insights */
        get: operations["ai_insights_api_v1_ai_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/forecasts/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Sales Forecast */
        get: operations["ai_sales_forecast_api_v1_ai_forecasts_sales_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/forecasts/demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Demand Forecast */
        get: operations["ai_demand_forecast_api_v1_ai_forecasts_demand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/inventory/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Inventory Recommendations */
        get: operations["ai_inventory_recommendations_api_v1_ai_inventory_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Dashboard */
        get: operations["ai_dashboard_api_v1_ai_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIDashboardResponse */
        AIDashboardResponse: {
            tenant: components["schemas"]["TenantContext"];
            summary?: components["schemas"]["AIExecutiveSummary"] | null;
            /** Insights */
            insights: components["schemas"]["AIInsight"][];
            /** Sales Forecast */
            sales_forecast: components["schemas"]["AISalesForecast"][];
            /** Demand Forecast */
            demand_forecast: components["schemas"]["AIDemandForecast"][];
            /** Inventory Recommendations */
            inventory_recommendations: components["schemas"]["AIInventoryRecommendation"][];
        };
        /** AIDemandForecast */
        AIDemandForecast: {
            /** Ai Ejecucion Id */
            ai_ejecucion_id: number;
            /** Empresa Key */
            empresa_key: number;
            /** Empresa */
            empresa: string;
            /** Producto Key */
            producto_key: number;
            /** Sku */
            sku: string;
            /** Producto */
            producto: string;
            /** Categoria */
            categoria?: string | null;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Horizonte Dias */
            horizonte_dias: number;
            /** Unidades Pronosticadas */
            unidades_pronosticadas: number;
            /** Limite Inferior */
            limite_inferior: number;
            /** Limite Superior */
            limite_superior: number;
            /** Amplitud Intervalo */
            amplitud_intervalo: number;
            /** Amplitud Intervalo Pct */
            amplitud_intervalo_pct?: number | null;
            /** Modelo */
            modelo: string;
            /** Origen Datos */
            origen_datos: string;
            /**
             * Generado En
             * Format: date-time
             */
            generado_en: string;
        };
        /** AIDemandForecastResponse */
        AIDemandForecastResponse: {
            tenant: components["schemas"]["TenantContext"];
            /** Count */
            count: number;
            /** Data */
            data: components["schemas"]["AIDemandForecast"][];
        };
        /** AIExecutiveSummary */
        AIExecutiveSummary: {
            /** Ai Ejecucion Id */
            ai_ejecucion_id: number;
            /** Empresa Key */
            empresa_key: number;
            /** Empresa */
            empresa: string;
            /** Origen Datos */
            origen_datos?: string | null;
            /** Version Modelo */
            version_modelo?: string | null;
            /** Algoritmo Ventas */
            algoritmo_ventas?: string | null;
            /** Algoritmo Demanda */
            algoritmo_demanda?: string | null;
            /** Mae Ventas */
            mae_ventas?: number | null;
            /** Mae Ventas Baseline */
            mae_ventas_baseline?: number | null;
            /** Mejora Ventas Pct */
            mejora_ventas_pct?: number | null;
            /** Mae Demanda */
            mae_demanda?: number | null;
            /** Mae Demanda Baseline */
            mae_demanda_baseline?: number | null;
            /** Mejora Demanda Pct */
            mejora_demanda_pct?: number | null;
            /** Filas Entrenamiento Ventas */
            filas_entrenamiento_ventas?: number | null;
            /** Filas Entrenamiento Demanda */
            filas_entrenamiento_demanda?: number | null;
            /** Venta Pronosticada Total */
            venta_pronosticada_total?: number | null;
            /** Venta Pronosticada Inferior */
            venta_pronosticada_inferior?: number | null;
            /** Venta Pronosticada Superior */
            venta_pronosticada_superior?: number | null;
            /** Productos Ventas Pronosticados */
            productos_ventas_pronosticados?: number | null;
            /** Primer Periodo Ventas */
            primer_periodo_ventas?: string | null;
            /** Ultimo Periodo Ventas */
            ultimo_periodo_ventas?: string | null;
            /** Demanda Pronosticada Total */
            demanda_pronosticada_total?: number | null;
            /** Demanda Pronosticada Inferior */
            demanda_pronosticada_inferior?: number | null;
            /** Demanda Pronosticada Superior */
            demanda_pronosticada_superior?: number | null;
            /** Productos Demanda Pronosticados */
            productos_demanda_pronosticados?: number | null;
            /** Primera Fecha Demanda */
            primera_fecha_demanda?: string | null;
            /** Ultima Fecha Demanda */
            ultima_fecha_demanda?: string | null;
            /** Recomendaciones Inventario */
            recomendaciones_inventario?: number | null;
            /** Productos Criticos */
            productos_criticos?: number | null;
            /** Productos Riesgo Alto */
            productos_riesgo_alto?: number | null;
            /** Productos Riesgo Medio */
            productos_riesgo_medio?: number | null;
            /** Productos Riesgo Bajo */
            productos_riesgo_bajo?: number | null;
            /** Productos A Reponer */
            productos_a_reponer?: number | null;
            /** Unidades Reposicion Sugeridas */
            unidades_reposicion_sugeridas?: number | null;
            /** Cobertura Promedio Dias */
            cobertura_promedio_dias?: number | null;
            /** Ultima Actualizacion Modelo */
            ultima_actualizacion_modelo?: string | null;
        };
        /** AIInsight */
        AIInsight: {
            /** Id */
            id: number;
            /** Ai Ejecucion Id */
            ai_ejecucion_id: number;
            /** Empresa Key */
            empresa_key: number;
            /** Empresa */
            empresa: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "VENTAS" | "DEMANDA" | "INVENTARIO" | "MODELO" | "OPERACION";
            /**
             * Severidad
             * @enum {string}
             */
            severidad: "INFO" | "BAJA" | "MEDIA" | "ALTA" | "CRITICA";
            /** Codigo */
            codigo: string;
            /** Titulo */
            titulo: string;
            /** Descripcion */
            descripcion: string;
            /** Accion Recomendada */
            accion_recomendada?: string | null;
            /** Valor */
            valor?: number | null;
            /** Unidad */
            unidad?: string | null;
            /** Orden */
            orden: number;
            /** Rule Version */
            rule_version: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Generado En
             * Format: date-time
             */
            generado_en: string;
        };
        /** AIInsightsResponse */
        AIInsightsResponse: {
            tenant: components["schemas"]["TenantContext"];
            /** Count */
            count: number;
            /** Data */
            data: components["schemas"]["AIInsight"][];
        };
        /** AIInventoryRecommendation */
        AIInventoryRecommendation: {
            /** Ai Ejecucion Id */
            ai_ejecucion_id: number;
            /** Empresa Key */
            empresa_key: number;
            /** Empresa */
            empresa: string;
            /** Producto Key */
            producto_key: number;
            /** Sku */
            sku: string;
            /** Producto */
            producto: string;
            /** Categoria */
            categoria?: string | null;
            /** Almacen Key */
            almacen_key: number;
            /** Almacen */
            almacen: string;
            /**
             * Fecha Referencia
             * Format: date
             */
            fecha_referencia: string;
            /** Stock Actual */
            stock_actual: number;
            /** Stock Minimo */
            stock_minimo: number;
            /** Demanda 30D */
            demanda_30d: number;
            /** Stock Objetivo */
            stock_objetivo: number;
            /** Cantidad Sugerida */
            cantidad_sugerida: number;
            /** Cobertura Dias */
            cobertura_dias?: number | null;
            /**
             * Riesgo
             * @enum {string}
             */
            riesgo: "BAJO" | "MEDIO" | "ALTO" | "CRITICO";
            /** Riesgo Orden */
            riesgo_orden: number;
            /** Requiere Reposicion */
            requiere_reposicion: boolean;
            /** Motivo */
            motivo: string;
            /**
             * Generado En
             * Format: date-time
             */
            generado_en: string;
        };
        /** AIInventoryRecommendationsResponse */
        AIInventoryRecommendationsResponse: {
            tenant: components["schemas"]["TenantContext"];
            /** Count */
            count: number;
            /** Data */
            data: components["schemas"]["AIInventoryRecommendation"][];
        };
        /** AISalesForecast */
        AISalesForecast: {
            /** Ai Ejecucion Id */
            ai_ejecucion_id: number;
            /** Empresa Key */
            empresa_key: number;
            /** Empresa */
            empresa: string;
            /** Producto Key */
            producto_key: number;
            /** Sku */
            sku: string;
            /** Producto */
            producto: string;
            /** Categoria */
            categoria?: string | null;
            /**
             * Periodo
             * Format: date
             */
            periodo: string;
            /** Venta Neta Pronosticada */
            venta_neta_pronosticada: number;
            /** Limite Inferior */
            limite_inferior: number;
            /** Limite Superior */
            limite_superior: number;
            /** Amplitud Intervalo */
            amplitud_intervalo: number;
            /** Amplitud Intervalo Pct */
            amplitud_intervalo_pct?: number | null;
            /** Modelo */
            modelo: string;
            /** Origen Datos */
            origen_datos: string;
            /**
             * Generado En
             * Format: date-time
             */
            generado_en: string;
        };
        /** AISalesForecastResponse */
        AISalesForecastResponse: {
            tenant: components["schemas"]["TenantContext"];
            /** Count */
            count: number;
            /** Data */
            data: components["schemas"]["AISalesForecast"][];
        };
        /** AISummaryResponse */
        AISummaryResponse: {
            tenant: components["schemas"]["TenantContext"];
            data?: components["schemas"]["AIExecutiveSummary"] | null;
        };
        /** AuthMeResponse */
        AuthMeResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email: string | null;
            /** Nombres */
            nombres?: string | null;
            /** Apellidos */
            apellidos?: string | null;
            /** Memberships */
            memberships: components["schemas"]["Membership"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Environment */
            environment: string;
        };
        /** Membership */
        Membership: {
            /**
             * Membership Id
             * Format: uuid
             */
            membership_id: string;
            /**
             * Empresa Id
             * Format: uuid
             */
            empresa_id: string;
            /** Empresa Key */
            empresa_key?: number | null;
            /** Empresa */
            empresa: string;
            /** Rol */
            rol: string;
            /** Empresa Activa */
            empresa_activa: boolean;
            /** Membresia Activa */
            membresia_activa: boolean;
        };
        /** TenantContext */
        TenantContext: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Empresa Id
             * Format: uuid
             */
            empresa_id: string;
            /** Empresa Key */
            empresa_key: number;
            /** Empresa */
            empresa: string;
            /** Rol */
            rol: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_db_api_v1_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
        };
    };
    ai_summary_api_v1_ai_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Empresa-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_insights_api_v1_ai_insights_get: {
        parameters: {
            query?: {
                severidad?: ("INFO" | "BAJA" | "MEDIA" | "ALTA" | "CRITICA") | null;
                tipo?: ("VENTAS" | "DEMANDA" | "INVENTARIO" | "MODELO" | "OPERACION") | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Empresa-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIInsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_sales_forecast_api_v1_ai_forecasts_sales_get: {
        parameters: {
            query?: {
                producto_key?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Empresa-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISalesForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_demand_forecast_api_v1_ai_forecasts_demand_get: {
        parameters: {
            query?: {
                producto_key?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Empresa-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIDemandForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_inventory_recommendations_api_v1_ai_inventory_recommendations_get: {
        parameters: {
            query?: {
                riesgo?: ("BAJO" | "MEDIO" | "ALTO" | "CRITICO") | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Empresa-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIInventoryRecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_dashboard_api_v1_ai_dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Empresa-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
